const dataForUsuarios = [
	{
		title: 'Usuario',
		inputs: [
			{
				label: 'Correo',
				placeholder: 'Escriba su correo electronico',
				type: 'text',
				htmlFor: 'email_usu',
				id: 'email_usu',
				name: 'email_usu',
				required: true,
				autoFocus: true,
			},
			{
				label: 'Contraseña',
				placeholder: 'Escriba su contraseña',
				type: 'password',
				htmlFor: 'pass_usu',
				id: 'pass_usu',
				name: 'pass_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Confimar',
				placeholder: 'confirme su contraseña',
				type: 'password',
				htmlFor: 'conf_pass_usu',
				id: 'conf_pass_usu',
				required: true,
				autoFocus: false,
			},
		],
	},
	{
		title: 'Datos Personales',
		inputs: [
			{
				label: 'Identificacion',
				placeholder: 'Escriba su Identificacion',
				type: 'text',
				htmlFor: 'id_usu',
				id: 'id_usu',
				name: 'id_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Nombres',
				placeholder: 'Escriba sus nombres',
				type: 'text',
				htmlFor: 'nom_usu',
				id: 'nom_usu',
				name: 'nom_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Apellidos',
				placeholder: 'Escriba sus apellidos',
				type: 'text',
				htmlFor: 'ape_usu',
				id: 'ape_usu',
				name: 'ape_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Direccion',
				placeholder: 'Escriba su direccion',
				type: 'text',
				htmlFor: 'dir_usu',
				id: 'dir_usu',
				name: 'dir_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Ciudad',
				placeholder: 'Escriba su ciudad',
				type: 'text',
				htmlFor: 'ciu_usu',
				id: 'ciu_usu',
				name: 'ciu_usu',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Celular',
				placeholder: 'Escriba su celular',
				type: 'number',
				htmlFor: 'cel_usu',
				id: 'cel_usu',
				name: 'cel_usu',
				required: true,
				autoFocus: false,
			},
		],
	},
]

export default dataForUsuarios
