const dataForFallecidos = [
	{
		title: 'Fallecidos',
		inputs: [
			{
				label: 'Identificacion',
				placeholder: 'Escriba su identificacion',
				type: 'number',
				htmlFor: 'id_fa',
				id: 'id_fa',
				name: 'id_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Nombres',
				placeholder: 'Escriba sus nombres',
				type: 'text',
				htmlFor: 'nom_fa',
				id: 'nom_fa',
				name: 'nom_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Apellidos',
				placeholder: 'Escriba sus apellidos',
				type: 'text',
				htmlFor: 'ape_fa',
				id: 'ape_fa',
				name: 'ape_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Parentesco',
				placeholder: 'Escriba su parentesco',
				type: 'text',
				htmlFor: 'par_fa',
				id: 'par_fa',
				name: 'par_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Direccion',
				placeholder: 'Escriba su direccion',
				type: 'text',
				htmlFor: 'dir_fa',
				id: 'dir_fa',
				name: 'dir_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Ciudad',
				placeholder: 'Escriba su ciudad',
				type: 'text',
				htmlFor: 'ciu_fa',
				id: 'ciu_fa',
				name: 'ciu_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Cod defuncion',
				placeholder: 'Escriba codigo',
				type: 'text',
				htmlFor: 'cod_fa',
				id: 'cod_fa',
				name: 'cod_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Certi defuncion',
				placeholder: 'Escriba codigo',
				type: 'text',
				htmlFor: 'ceri_fa',
				id: 'ceri_fa',
				name: 'ceri_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Fecha de muerte',
				type: 'date',
				htmlFor: 'date_dead_fa',
				id: 'date_dead_fa',
				name: 'date_dead_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Fecha de inhumacion',
				type: 'date',
				htmlFor: 'date_in_fa',
				id: 'date_in_fa',
				name: 'date_in_fa',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Causa de muerte',
				placeholder: 'Escriba causa de muerte',
				type: 'text',
				htmlFor: 'cause_fa',
				id: 'cause_fa',
				name: 'cause_fa',
				required: true,
				autoFocus: false,
			},
		],
	},
]

export default dataForFallecidos
