const dataForSolicitantes = [
	{
		title: 'Solicitantes',
		inputs: [
			{
				label: 'Identificacion',
				placeholder: 'Escriba su identificacion',
				type: 'number',
				htmlFor: 'id_so',
				id: 'id_so',
				name: 'id_so',
				required: true,
				autoFocus: true,
			},
			{
				label: 'Nombres',
				placeholder: 'Escriba sus nombres',
				type: 'text',
				htmlFor: 'nom_so',
				id: 'nom_so',
				name: 'nom_so',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Apellidos',
				placeholder: 'Escriba sus apellidos',
				type: 'text',
				htmlFor: 'ape_so',
				id: 'ape_so',
				name: 'ape_so',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Parentesco',
				placeholder: 'Escriba su parentesco',
				type: 'text',
				htmlFor: 'par_so',
				id: 'par_so',
				name: 'par_so',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Direccion',
				placeholder: 'Escriba su direccion',
				type: 'text',
				htmlFor: 'dir_so',
				id: 'dir_so',
				name: 'dir_so',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Ciudad',
				placeholder: 'Escriba su ciudad',
				type: 'text',
				htmlFor: 'ciu_so',
				id: 'ciu_so',
				name: 'ciu_so',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Celular',
				placeholder: 'Escriba su celular',
				type: 'number',
				htmlFor: 'cel_so',
				id: 'cel_so',
				name: 'cel_so',
				required: true,
				autoFocus: false,
			},
		],
	},
]

export default dataForSolicitantes
