const dataForBovedas = [
	{
		title: 'Propietario',
		inputs: [
			{
				label: 'Identificacion',
				placeholder: 'Escriba su identificacion',
				type: 'number',
				htmlFor: 'id_pro',
				id: 'id_pro',
				name: 'id_pro',
				required: true,
				autoFocus: true,
			},
			{
				label: 'Nombres',
				placeholder: 'Escriba sus nombres',
				type: 'text',
				htmlFor: 'nom_pro',
				id: 'nom_pro',
				name: 'nom_pro',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Apellidos',
				placeholder: 'Escriba sus apellidos',
				type: 'text',
				htmlFor: 'ape_pro',
				id: 'ape_pro',
				name: 'ape_pro',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Direccion',
				placeholder: 'Escriba su direccion',
				type: 'text',
				htmlFor: 'dir_pro',
				id: 'dir_pro',
				name: 'dir_pro',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Ciudad',
				placeholder: 'Escriba su ciudad',
				type: 'text',
				htmlFor: 'ciu_pro',
				id: 'ciu_pro',
				name: 'ciu_pro',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Celular',
				placeholder: 'Escriba su celular',
				type: 'number',
				htmlFor: 'cel_pro',
				id: 'cel_pro',
				name: 'cel_pro',
				required: true,
				autoFocus: false,
			},
		],
	},
	{
		title: 'Boveda',
		inputs: [
			{
				label: 'Codigo',
				placeholder: 'Escriba codigo boveda',
				type: 'text',
				htmlFor: 'cod_bo',
				id: 'cod_bo',
				name: 'cod_bo',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Cant Cilindros',
				placeholder: 'Cantidad de cilindros',
				type: 'text',
				htmlFor: 'cant_cilindros_bo',
				id: 'cant_cilindros_bo',
				name: 'cant_cilindros_bo',
				required: true,
				autoFocus: false,
			},
			{
				label: 'Cant Osarios',
				placeholder: 'Cantidad de osarios',
				type: 'text',
				htmlFor: 'cant_nichos_bo',
				id: 'cant_nichos_bo',
				name: 'cant_nichos_bo',
				required: true,
				autoFocus: false,
			},
		],
	},
]

export default dataForBovedas
